SELECT 1
USE APGRUPOS INDEX APGRUPOS
SELECT 2
USE APNOMINA INDEX APNOMINA
SELECT 3
USE APPERSON INDEX APPERSO2
SELECT 4
USE APCONPER INDEX APCONPER
SELECT 5
USE APPAGGEN INDEX APPAGGE2, APPAGGE1, APPAGGE3
SELECT 6
USE APPAGCON INDEX APPAGCO1
SELECT 7
USE APHISGEN INDEX APHISGE1, APHISGE2, APHISGE3
SELECT 8
USE APHISCON INDEX APHISCO1, APHISCO2

STORE .T. TO WCERRANDO
DO WHILE WCERRANDO
   @ 4,0 CLEAR
   @ 04,00 SAY "CIERRA DE PERIODO DE PAGO"
   @ 5,0 TO 18,60
   @ 06,02 SAY "GRUPO DE NOMINAS  :"
   @ 08,02 SAY "CODIGO DE NOMINA  :"
   @ 10,02 SAY "LAPSO DE APERTURA :"
   @ 12,02 SAY "PERIODO ACTUAL    :"
   @ 14,02 SAY "ESTADO ACTUAL     :"
   STORE .T. TO WGETGRUPO
   DO WHILE WGETGRUPO
      @ 06,21 GET WGRUPO
      READ
      IF WGRUPO = SPACE(2) .OR. READKEY()=12 .OR. READKEY()=268
         STORE .F. TO WCERRANDO
         EXIT
      ENDIF
      SELECT 1
      FIND &WGRUPO
      IF EOF()
         STORE "GRUPO DE NOMINAS NO REGISTRADO, VERIFIQUE" TO MES
         DO AVISO WITH MES
         LOOP
      ELSE
         @ 06,25 SAY DESCRI
         EXIT
      ENDIF
   ENDDO
   IF .NOT. WCERRANDO
      EXIT
   ENDIF

   STORE .T. TO WGETNOMI
   DO WHILE WGETNOMI
      @ 08,21 GET WNOMINA
      READ
      IF WNOMINA = SPACE(2) .OR. READKEY()=12 .OR. READKEY()=268
         STORE .F. TO WGETNOMI
         EXIT
      ENDIF
      STORE WGRUPO+WNOMINA TO WCLAVENOM
      SELECT 2
      FIND &WCLAVENOM
      IF EOF()
         STORE "NOMINA NO REGISTRADA PARA ESTE GRUPO, VERIFIQUE" TO MES
         DO AVISO WITH MES
         LOOP
      ELSE
         DO RECLOC
         @ 08,25 SAY DESCRI
         STORE LAPSO TO WLAPSO
         STORE APER2 TO WAPER2
         EXIT
      ENDIF
   ENDDO
   IF .NOT. WGETNOMI
      LOOP
   ENDIF
   *** DETERMINAR EL ESTADO POR ESCRITO
   STORE ESTADO TO WESTADO
   STORE SPACE(1) TO WESTADODES
   DO ESTADO
   ***
   @ 10,21 SAY STR(LAPSO,3,2)+" DIAS"
   @ 12,21 SAY DTOC(APER1)+" AL "+DTOC(APER2)
   @ 14,21 SAY STR(ESTADO,1)+" "+WESTADODES
   STORE "ES ESTA LA NOMINA QUE DESEA CERRAR ? (S/N)" TO TEX
   STORE "SN" TO WCH
   DO PREGUNTA
   IF WCH = "N"
      LOOP
   ENDIF
   IF ESTADO < 6
      STORE "ATENCION: "+WESTADODES+" NO ELABORADA, VERIFIQUE" TO MES
      DO AVISO WITH MES
      LOOP
   ENDIF
   STORE "OPCIONES: (C)ONTINUAR, (S)ALIR" TO TEX
   STORE "SC" TO WCH
   DO PREGUNTA
   IF WCH = "S"
      UNLOCK ALL
      LOOP
   ENDIF
   STORE "EFECTUANDO CIERRE DE PERIODO DE PAGO, FAVOR ESPERAR..." TO MES
   DO MENSAJE WITH MES

   *** ELIMINA LOS SOBRES DE PAGO ANTERIORES AL CIERRE ACTUAL
   STORE WGRUPO+WNOMINA+STR(YEAR(WAPER2))+STR(MONTH(WAPER2))+STR(DAY(WAPER2)) TO WCLAVEGEN
   STORE .T. TO WDELGEN
   DO WHILE WDELGEN
      SELECT 7
      SET ORDER TO 2
      FIND &WCLAVEGEN
      IF EOF()
         EXIT
      ENDIF
      STORE CEDULA TO WDELCED
      DO RECLOC
      DELETE
      UNLOCK
      *** BORRA LOS CONCEPTOS DEL SOBRE
      STORE WDELCED+STR(YEAR(WAPER2))+STR(MONTH(WAPER2))+STR(DAY(WAPER2)) TO WCLAVECON
      STORE .T. TO WDELCON
      DO WHILE WDELCON
         SELECT 8
         FIND &WCLAVECON
         IF EOF()
            EXIT
         ENDIF
         *** REVERSA MONTO PROCESADO
         STORE APHISCON->CEDULA+APHISCON->CONCEPTO TO WCLAVEPER
         SELECT 4
         FIND &WCLAVEPER
         IF EOF()
            STORE "CONCEPTO:"+APHISCON->CONCEPTO+" EN HISTORA DE:"+APHISCON->CEDULA+", NO REG.EN CONCEPTOS PERS." TO MES
            DO AVISO WITH MES
            STORE "POR LO TANTO NO SERA REVERSADO EL MONTO PROCESADO" TO MES
            DO AVISO WITH MES
         ELSE
            DO RECLOC
            REPLACE MONTOPRO WITH MONTOPRO-APPAGCON->MONTO
            UNLOCK
         ENDIF
         SELECT 8
         DO RECLOC
         DELETE
         UNLOCK
      ENDDO
   ENDDO
   SELECT 7
   SET ORDER TO 1

   *** TRANSFIERE DE APPAGGEN A APHISGEN
   SELECT 5
   FIND &WCLAVEGEN
   DO WHILE .NOT. EOF() .AND. GRUPO=WGRUPO .AND. NOMINA=WNOMINA .AND. FECHA2=WAPER2
      STORE "CEDULA: "+APPAGGEN->CEDULA TO MES
      DO MENSAJE WITH MES
      SELECT 7
      DO FILLOC
      APPEND BLANK
      UNLOCK
      DO RECLOC
      REPLACE CEDULA   WITH APPAGGEN->CEDULA
      REPLACE FECHA1   WITH APPAGGEN->FECHA1
      REPLACE FECHA2   WITH APPAGGEN->FECHA2
      REPLACE GRUPO    WITH APPAGGEN->GRUPO
      REPLACE NOMINA   WITH APPAGGEN->NOMINA
      REPLACE DIRE     WITH APPAGGEN->DIRE
      REPLACE DEPA     WITH APPAGGEN->DEPA
      REPLACE SECC     WITH APPAGGEN->SECC
      REPLACE CARGO    WITH APPAGGEN->CARGO
      REPLACE SUELDOH  WITH APPAGGEN->SUELDOH
      REPLACE SUELDOD  WITH APPAGGEN->SUELDOD
      REPLACE SUELDOP  WITH APPAGGEN->SUELDOP
      REPLACE TIPO     WITH APPAGGEN->TIPO
      UNLOCK
      FLUSH
      STORE APPAGGEN->CEDULA+STR(YEAR(APPAGGEN->FECHA2))+STR(MONTH(APPAGGEN->FECHA2))+STR(DAY(APPAGGEN->FECHA2)) TO WCLAVECON
      SELECT 6
      FIND &WCLAVECON
      DO WHILE .NOT. EOF() .AND. CEDULA=APPAGGEN->CEDULA .AND. FECHA2=APPAGGEN->FECHA2
         SELECT 8
         DO FILLOC
         APPEND BLANK
         UNLOCK
         DO RECLOC
         REPLACE CEDULA   WITH APPAGCON->CEDULA
         REPLACE FECHA1   WITH APPAGCON->FECHA1
         REPLACE FECHA2   WITH APPAGCON->FECHA2
         REPLACE CONCEPTO WITH APPAGCON->CONCEPTO
         REPLACE CANTIDAD WITH APPAGCON->CANTIDAD
         REPLACE MONTO    WITH APPAGCON->MONTO
         REPLACE SALDO    WITH APPAGCON->SALDO
         REPLACE ORIGEN   WITH "NOM"
         UNLOCK
         *** ACTUALIZA MONTO PROCESADO
         STORE APPAGCON->CEDULA+APPAGCON->CONCEPTO TO WCLAVEPER
         SELECT 4
         FIND &WCLAVEPER
         IF EOF()
           * STORE "CONCEPTO:"+APPAGCON->CONCEPTO+" DEL SOBRE DE:"+APPAGCON->CEDULA+", NO REG.EN CONCEPTOS PERS." TO MES
           * DO AVISO WITH MES
           * STORE "POR LO TANTO NO SERA ACTUALIZADO EL MONTO PROCESADO" TO MES
           * DO AVISO WITH MES
         ELSE
            DO RECLOC
            REPLACE MONTOPRO WITH MONTOPRO+APPAGCON->MONTO
            UNLOCK
         ENDIF
         FLUSH
         SELECT 6
         SKIP
      ENDDO
      SELECT 5
      SKIP
   ENDDO
   *** FIJAR NUEVOS VALORES DE LA NOMINA
   SELECT 2
   DO RECLOC
   REPLACE ESTADO    WITH 0
   UNLOCK
   ***
   STORE "CIERRE EFECTUADO SATISFACTORIAMENTE, OPRIMA <ENTER>" TO MES
   DO AVISO WITH MES
   UNLOCK ALL
ENDDO
CLOSE DATA
CLOSE INDEX
RETURN

