select 1
use apperson index apperso1
select 2
use apcon    index apcon
select 3
use aphisgen index aphisge1
select 4
use aphiscon index aphisco1
@ 4,0 CLEAR to 18,79
@ 5,0 TO 18,79
@ 04,00 SAY "HISTORICO INDIVIDUAL (NOM.CONCEPTUAL)"
@ 06,2 SAY "CEDULA                      :"
@ 08,2 SAY "NOMBRE                      :"
@ 10,2 SAY "CONCEPTO                    :"
@ 12,2 SAY "DESDE EL                    :"
@ 14,2 SAY "HASTA EL                    :"
@ 16,2 SAY "SALIDA (M/I)                :"
SAVE SCRE TO SCREPRI
STORE .F. TO WFLAGSCRE
STORE .T. TO WCARGANDO
DO WHILE WCARGANDO
   IF WFLAGSCRE
      @ 0,0 CLEAR
      RESTORE SCRE FROM SCREPRI
   ELSE
      STORE .T. TO WFLAGSCRE
   ENDIF
   @ 06,33 GET WCEDULA
   READ
   IF WCEDULA = SPACE(12) .OR.READKEY()=12.OR.READKEY()=268
      EXIT
   ENDIF
   SELECT 1
   FIND &WCEDULA
   IF EOF()
      STORE "NO REGISTRADA, VERIFIQUE." TO MES
      DO AVISO WITH MES
      LOOP
   ENDIF
   STORE APELLIDOS  TO XAPELLIDOS
   STORE NOMBRES    TO XNOMBRES
   @ 08,33 SAY RTRIM(XAPELLIDOS)+", "+XNOMBRES
   STORE .T. TO WGETCON
   DO WHILE WGETCON
      STORE SPACE(4) TO WCONCEPTO
      @ 10,33 GET WCONCEPTO 
      READ
      IF WCONCEPTO=SPACE(4).OR.READKEY()=12.OR.READKEY()=268
         STORE .F. TO WGETCON
         EXIT
      ENDIF
      SELECT 2
      FIND &WCONCEPTO
      IF EOF()
         STORE "CONCEPTO NO REGISTRADO, VERIFIQUE" TO MES
         DO AVISO WITH MES
      ELSE
         STORE DESCRI TO WCONCEPDES
         @ 10,38 SAY WCONCEPDES
         EXIT
      ENDIF 
   ENDDO
   IF .NOT. WGETCON
      LOOP
   ENDIF
   STORE CTOD("  -  -  ") TO WDESDE
   STORE CTOD("  -  -  ") TO WHASTA 
   @ 12,33 GET WDESDE
   @ 14,33 GET WHASTA
   READ
   IF WHASTA<WDESDE
      STORE "ERROR EN FECHAS, VERIFIQUE." TO MES
      DO AVISO WITH MES
      LOOP
   ENDIF
   STORE "SELECCIONE LA SALIDA : (M)ONITOR, (I)MPRESORA" TO TEX
   STORE "MI" TO WCH
   DO PREGUNTA
   STORE WCH TO WSALIDA
   IF WSALIDA = "M"
      STORE 20 TO WSALTO
      STORE "MONITOR" TO WSALIDES
   ELSE
      STORE 55 TO WSALTO
      STORE "IMPRESORA" TO WSALIDES
   ENDIF
   @ 16,33 SAY WSALIDES
   STORE "OPCIONES: (C)ONTINUAR, (R)ECHAZAR" TO TEX
   STORE "CR" TO WCH
   DO PREGUNTA
   IF WCH = "R"
      LOOP
   ENDIF
   *** APROXIMACION A LA DATA SOLICITADA
   *** OJO, SERIA MAS RAPIDO BUSCAR POR APHISGEN CON LA MISMA TECNICA
   STORE WCEDULA TO WCLAVEPER
   SELECT 4
   FIND &WCLAVEPER
   IF .NOT. EOF()
      STORE RECNO() TO WSTARTPER
      STORE WCEDULA+STR(YEAR(WDESDE)) TO WCLAVEPER
      FIND &WCLAVEPER
      IF .NOT. EOF()
         STORE RECNO() TO WSTARTPER
         STORE WCEDULA+STR(YEAR(WDESDE))+STR(MONTH(WDESDE)) TO WCLAVEPER
         FIND &WCLAVEPER
         IF .NOT. EOF()
            STORE RECNO() TO WSTARTPER
            STORE WCEDULA+STR(YEAR(WDESDE))+STR(MONTH(WDESDE))+STR(DAY(WDESDE)) TO WCLAVEPER
            FIND &WCLAVEPER 
            IF .NOT. EOF()
               STORE RECNO() TO WSTARTPER
            ENDIF
         ENDIF
      ENDIF
   ELSE
      STORE "NO HAY HISTORICOS PARA ESTA PERSONA" TO MES
      DO AVISO WITH MES
      LOOP              
   ENDIF
   IF WSALIDA = "M"
      @ 0,0 CLEAR
   ELSE
      SET DEVI TO PRINT
   ENDIF
   STORE 100 TO WLINEA
   STORE 0   TO WPAGINA
   STORE 0   TO WTOTINF
   SELECT 4
   GO WSTARTPER
   DO WHILE .NOT. EOF() .AND. CEDULA = WCEDULA
      IF FECHA2 < WDESDE 
         SELECT 4
         SKIP
         LOOP
      ENDIF
      IF FECHA2 > WHASTA
         EXIT
      ENDIF
      IF CONCEPTO <> WCONCEPTO
         SELECT 4
         SKIP
         LOOP
      ENDIF
      STORE WLINEA+1 TO WLINEA
      IF WLINEA > WSALTO
         STORE WPAGINA + 1 TO WPAGINA
         IF WSALIDA = "M"
            IF WPAGINA > 1
               STORE "OPRIMA <ENTER> PARA CONTINUAR, <ESC> PARA SALIR" TO MES
               DO AVISO WITH MES
               IF READKEY()=12.OR.READKEY()=268
                  EXIT
               ENDIF
            ENDIF
            @ 0,0 CLEAR
         ENDIF
         @ 1,00 SAY CHR(14)+QQWW
         @ 2,00 SAY "HISTORICO INDIVIDUAL DEL CONCEPTO "+WCONCEPTO+" "+WCONCEPDES
         @ 3,00 SAY "CEDULA :"+WCEDULA+" "+RTRIM(XAPELLIDOS)+", "+XNOMBRES
         @ 3,60 SAY "PAGINA:"+STR(WPAGINA,4)

         @ 4,00 SAY "DESDE EL "+DTOC(WDESDE)+" HASTA EL "+DTOC(WHASTA)
         @ 4,60 SAY "FECHA :"+DTOC(DATE())

         @ 6,00 SAY "FECHA    CANTIDAD         MONTO         SALDO"
         @ 7,00 SAY "-------- -------- ------------- -------------"
         STORE 8 TO WLINEA
      ENDIF
      @ WLINEA,00  SAY FECHA2
      @ WLINEA,09  SAY CANTIDAD  PICTURE "#####.##"
      @ WLINEA,18  SAY MONTO     PICTURE "##,###,###.##"
      STORE WTOTINF+MONTO TO WTOTINF
      IF SALDO > 0
         @ WLINEA,32 SAY SALDO   PICTURE "##,###,###.##"
      ENDIF
      SELECT 4
      SKIP
   ENDDO
   IF WTOTINF > 0
      STORE WLINEA+1 TO WLINEA
      @ WLINEA,00 SAY "TOTAL INFORME :"
      @ WLINEA,18 SAY WTOTINF PICTURE "##,###,###.##"
   ENDIF
   IF WSALIDA = "M"
      STORE "OPRIMA <ENTER> PARA FINALIZAR" TO MES
      DO AVISO WITH MES
   ELSE
      SET DEVI TO SCRE
   ENDIF
ENDDO
CLOSE DATA
CLOSE INDEX
RETURN
