         store 0 to xmonto
         if apperson->sueldop=32587
            store    25000 to xmonto
         endif
         if apperson->sueldop=31293
            store    23750 to xmonto
         endif
         if apperson->sueldop=30000
            store    22500 to xmonto
         endif
         if apperson->sueldop=24000
            store    16250 to xmonto
         endif
         if apperson->sueldop=17969
            store    12500 to xmonto
         endif
         if apperson->sueldop=21344
            store    13750 to xmonto
         endif
         if apperson->sueldop=14229
            store    11250 to xmonto
         endif
         if apperson->sueldop=21151
            store    15000 to xmonto
         endif
         if apperson->sueldop=16755
            store    11250 to xmonto
         endif
         if apperson->sueldop=24883
            store    15000 to xmonto
         endif
         if apperson->sueldop=17000
            store    13750 to xmonto
         endif
         if apperson->sueldop=25804
            store    18750 to xmonto
         endif
         return
